service: aws-node # NOTE: update this with your service name
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  stream:
    handler: ./functions/stream.handler
    events:
      - http:
          path: stream
          method: get

custom:
  # https://www.serverless.com/plugins/serverless-esbuild
  esbuild:
    config: "./esbuild.config.js"
